

// Generated by https://quicktype.io

export interface Capacitadores {
  id:             number;
  nombre:         string;
  identificacion: string;
  carrera:        string;
  telefono:       string;
  descripcion:    string;
}
