// Generated by https://quicktype.io

import { AreasConocimiento } from "./areasConocimiento.interfaace";

export interface Capacitadores {
  id:              number;
  nombreDocente:   string;
  apellidoDocente: string;
  identificacion:  string;
  correo:          string;
  carrera:         string;
  telefono:        string;
  descripcion:     string;
  estado:          'Activo' | 'Ocupado';
  areas:           AreasConocimiento[];
}
