// Generated by https://quicktype.io

export interface Eventos {
  id:          number;
  titulo:      string;
  descripcion: string;
  duracion:    string;
  fecha:       string;
  imgen:       string;
}
