// Generated by https://quicktype.io

import { AreaConocimiento } from "./areasConocimiento.interfaace";

export interface Evento {
  id:          number;
  titulo:      string;
  descripcion: string;
  duracion:    number;
  fecha:       string;
  imagen:      string;
  estado:      'Confirmado' | 'Rechazado';
  inicioHora:  string;
  modalidad:   'Presencial' | 'Virtual';
  areas:       AreaConocimiento[];
}
